# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_via_trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
